package names;

import data.threat.CreatureType;

public enum FactionType {
	DARK_CULT("Dark Cult"),
	HERETICAL_SECT("Heretical Sect"),
	NATIONAL_CHURCH("National Church"),
	RELIGIOUS_ORDER("Religious Order"),
	RELIGIOUS_SECT("Religious Sect"),
	DRUID_CIRCLE("Druid Circle"),
	MONASTIC_ORDER("Monastic Order"),


	ART_MOVEMENT("Art Movement"),
	BARD_COLLEGE("Bard College"),
	BEGGAR_GUILD("Beggar's Guild"),
	BLACK_MARKET("Black Market"),
	BROTHERHOOD("Brotherhood"),
	CITY_GUARD("City Guard"),
	CONSPIRACY("Conspiracy"),
	CRAFT_GUILD("Craft Guild"),
	CRIME_FAMILY("Crime Family"),
	CRIME_RING("Crime Ring"),
	EXPLORER_CLUB("Explorer's Club"),
	FREE_COMPANY("Free Company"),
	GOURMAND_CLUB("Gourmand Club"),
	HEIST_CREW("Heist Crew"),
	HIGH_COUNCIL("High Council"),
	HIRED_KILLERS("Hired Killers"),
	LOCAL_MILITIA("Local Militia"),
	NOBLE_HOUSE("Noble House"),
	OUTLANDER_CLAN("Outlander Clan"),
	OUTLAW_GANG("Outlaw Gang"),
	POLITICAL_PARTY("Political Party"),
	KNIGHTLY_ORDER("Knightly Order"),
	RESISTANCE("Resistance"),
	ROYAL_ARMY("Royal Army"),
	ROYAL_HOUSE("Royal House"),
	SCHOLAR_CIRCLE("Scholar's Circle"),
	SECRET_SOCIETY("Secret Society"),
	SPY_NETWORK("Spy Network"),
	STREET_ARTISTS("Street Artists"),
	STREET_GANG("Street Gang"),
	THEATER_TROUPE("Theater Troupe"),
	TRADE_COMPANY("Trade Company"),
	WIZARD_CIRCLE("Wizard Circle");

	private static final FactionType[] ABERRATION = {DARK_CULT,DARK_CULT,DARK_CULT,DARK_CULT,DARK_CULT,HERETICAL_SECT,HERETICAL_SECT,HERETICAL_SECT,NATIONAL_CHURCH,RELIGIOUS_ORDER,RELIGIOUS_SECT,
			ART_MOVEMENT,BROTHERHOOD,CONSPIRACY,CRAFT_GUILD,EXPLORER_CLUB,NOBLE_HOUSE,SCHOLAR_CIRCLE,SECRET_SOCIETY,STREET_ARTISTS,BARD_COLLEGE,THEATER_TROUPE,WIZARD_CIRCLE};
	private static final FactionType[] BEAST = {DARK_CULT,DRUID_CIRCLE,OUTLANDER_CLAN,OUTLAW_GANG,EXPLORER_CLUB,WIZARD_CIRCLE};
	private static final FactionType[] CELESTIAL = {DARK_CULT,HERETICAL_SECT,NATIONAL_CHURCH,RELIGIOUS_ORDER,RELIGIOUS_SECT,MONASTIC_ORDER,
			BROTHERHOOD,CONSPIRACY,KNIGHTLY_ORDER,ROYAL_ARMY,ROYAL_HOUSE,NOBLE_HOUSE,SECRET_SOCIETY};
	private static final FactionType[] CONSTRUCT = {CONSPIRACY,CRAFT_GUILD,CRAFT_GUILD,CRAFT_GUILD,CRAFT_GUILD,CRIME_FAMILY,FREE_COMPANY,HIRED_KILLERS,OUTLAW_GANG,RESISTANCE,
			SCHOLAR_CIRCLE,SECRET_SOCIETY,SPY_NETWORK,WIZARD_CIRCLE};
	private static final FactionType[] DRAGON = {DARK_CULT,HERETICAL_SECT,NATIONAL_CHURCH,RELIGIOUS_ORDER,RELIGIOUS_SECT,MONASTIC_ORDER,
			CONSPIRACY,CRIME_FAMILY,CRIME_RING,GOURMAND_CLUB,HIGH_COUNCIL,KNIGHTLY_ORDER,NOBLE_HOUSE,OUTLANDER_CLAN,OUTLAW_GANG,POLITICAL_PARTY,ROYAL_HOUSE,SCHOLAR_CIRCLE,SECRET_SOCIETY,
			SPY_NETWORK,WIZARD_CIRCLE};
	private static final FactionType[] ELEMENTAL = {DARK_CULT,HERETICAL_SECT,NATIONAL_CHURCH,RELIGIOUS_ORDER,RELIGIOUS_SECT,DRUID_CIRCLE,MONASTIC_ORDER,OUTLANDER_CLAN};
	private static final FactionType[] FEY = {DARK_CULT,RELIGIOUS_ORDER,DRUID_CIRCLE,MONASTIC_ORDER,			ART_MOVEMENT,BEGGAR_GUILD,
			BLACK_MARKET,CONSPIRACY,CRIME_RING,GOURMAND_CLUB,HEIST_CREW,KNIGHTLY_ORDER,OUTLAW_GANG,RESISTANCE,SECRET_SOCIETY,SPY_NETWORK,STREET_ARTISTS,STREET_GANG,BARD_COLLEGE,THEATER_TROUPE};
	private static final FactionType[] FIEND = {DARK_CULT,HERETICAL_SECT,NATIONAL_CHURCH,RELIGIOUS_ORDER,RELIGIOUS_SECT,
			BROTHERHOOD,CONSPIRACY,CRIME_FAMILY,CRIME_RING,HIRED_KILLERS,KNIGHTLY_ORDER,NOBLE_HOUSE,OUTLAW_GANG,POLITICAL_PARTY,RESISTANCE,ROYAL_HOUSE,SCHOLAR_CIRCLE,SECRET_SOCIETY,
			SPY_NETWORK,TRADE_COMPANY,WIZARD_CIRCLE};
	private static final FactionType[] GIANT = {DRUID_CIRCLE,MONASTIC_ORDER,FREE_COMPANY,GOURMAND_CLUB,OUTLANDER_CLAN,OUTLANDER_CLAN,OUTLANDER_CLAN,OUTLANDER_CLAN,OUTLANDER_CLAN,OUTLAW_GANG,OUTLAW_GANG};
	private static final FactionType[] HUMANOID = FactionType.values();
	private static final FactionType[] MONSTROSITY = {DARK_CULT,DRUID_CIRCLE,OUTLANDER_CLAN,OUTLAW_GANG,EXPLORER_CLUB,WIZARD_CIRCLE};
	private static final FactionType[] OOZE = {DARK_CULT,DRUID_CIRCLE,BEGGAR_GUILD,BLACK_MARKET,CRIME_RING,GOURMAND_CLUB,OUTLANDER_CLAN,OUTLAW_GANG,EXPLORER_CLUB,SPY_NETWORK,STREET_GANG,WIZARD_CIRCLE};
	private static final FactionType[] PLANT = {DARK_CULT,DRUID_CIRCLE,OUTLANDER_CLAN,OUTLAW_GANG,EXPLORER_CLUB,WIZARD_CIRCLE};
	private static final FactionType[] UNDEAD = FactionType.values();
	public static FactionType[] getFactionList(CreatureType type) {
		switch(type) {
		case ABERRATION: return ABERRATION;
		case BEAST: return BEAST;
		case CELESTIAL:return CELESTIAL;
		case CONSTRUCT:return CONSTRUCT;
		case DRAGON:return DRAGON;
		case ELEMENTAL:return ELEMENTAL;
		case FEY:return FEY;
		case FIEND:return FIEND;
		case GIANT:return GIANT;
		case HUMANOID:return HUMANOID;
		case MONSTROSITY:return MONSTROSITY;
		case OOZE:return OOZE;
		case PLANT:return PLANT;
		case UNDEAD:return UNDEAD;
		default: throw new UnsupportedOperationException("faction list not implemented for type: "+type.toString());
		}
	}

	String text;

	FactionType(String text) {
		this.text = text;
	}

	public String getText() {
		return text;
	}
	public String toString() {
		return text;
	}
	public boolean isFaith() {
		return FactionNameGenerator.isFaith(this);
	}
}
