package names;

import data.threat.CreatureType;

public enum FactionType {
	DARK_CULT("Dark Cult"),
	HERETICAL_SECT("Heretical Sect"),
	NATIONAL_CHURCH("National Church"),
	RELIGIOUS_ORDER("Religious Order"),
	RELIGIOUS_SECT("Religious Sect"),


	ART_MOVEMENT("Art Movement"),
	BEGGAR_GUILD("Beggar's Guild"),
	BLACK_MARKET("Black Market"),
	BROTHERHOOD("Brotherhood"),
	CITY_GUARD("City Guard"),
	CONSPIRACY("Conspiracy"),
	CRAFT_GUILD("Craft Guild"),
	CRIME_FAMILY("Crime Family"),
	CRIME_RING("Crime Ring"),
	EXPLORER_CLUB("Explorer's Club"),
	FREE_COMPANY("Free Company"),
	GOURMAND_CLUB("Gourmand Club"),
	HEIST_CREW("Heist Crew"),
	HIGH_COUNCIL("High Council"),
	HIRED_KILLERS("Hired Killers"),
	LOCAL_MILITIA("Local Militia"),
	NOBLE_HOUSE("Noble House"),
	OUTLANDER_CLAN("Outlander Clan"),
	OUTLAW_GANG("Outlaw Gang"),
	POLITICAL_PARTY("Political Party"),
	RESISTANCE("Resistance"),
	ROYAL_ARMY("Royal Army"),
	ROYAL_HOUSE("Royal House"),
	SCHOLAR_CIRCLE("Scholar's Circle"),
	SECRET_SOCIETY("Secret Society"),
	SPY_NETWORK("Spy Network"),
	STREET_ARTISTS("Street Artists"),
	STREET_GANG("Street Gang"),
	STREET_MUSICIANS("Street Musicians"),
	THEATER_TROUPE("Theater Troupe"),
	TRADE_COMPANY("Trade Company");

	public static final FactionType[] ABERRATION = {DARK_CULT,DARK_CULT,DARK_CULT,DARK_CULT,DARK_CULT,HERETICAL_SECT,HERETICAL_SECT,HERETICAL_SECT,NATIONAL_CHURCH,RELIGIOUS_ORDER,RELIGIOUS_SECT,
			ART_MOVEMENT,BROTHERHOOD,CONSPIRACY,CRAFT_GUILD,EXPLORER_CLUB,NOBLE_HOUSE,SCHOLAR_CIRCLE,SECRET_SOCIETY,STREET_ARTISTS,STREET_MUSICIANS,THEATER_TROUPE};
	public static final FactionType[] BEAST = {DARK_CULT,OUTLANDER_CLAN,OUTLAW_GANG,EXPLORER_CLUB};
	public static final FactionType[] CELESTIAL = {DARK_CULT,HERETICAL_SECT,NATIONAL_CHURCH,RELIGIOUS_ORDER,RELIGIOUS_SECT,BROTHERHOOD,CONSPIRACY,ROYAL_ARMY,ROYAL_HOUSE,NOBLE_HOUSE,SECRET_SOCIETY};
	public static final FactionType[] CONSTRUCT = {CONSPIRACY,CRAFT_GUILD,CRAFT_GUILD,CRAFT_GUILD,CRIME_FAMILY,FREE_COMPANY,HIRED_KILLERS,OUTLAW_GANG,RESISTANCE,SCHOLAR_CIRCLE,SECRET_SOCIETY,SPY_NETWORK};
	public static final FactionType[] DRAGON = {DARK_CULT,HERETICAL_SECT,NATIONAL_CHURCH,RELIGIOUS_ORDER,RELIGIOUS_SECT,
			CONSPIRACY,CRIME_FAMILY,CRIME_RING,GOURMAND_CLUB,HIGH_COUNCIL,NOBLE_HOUSE,OUTLANDER_CLAN,OUTLAW_GANG,POLITICAL_PARTY,ROYAL_HOUSE,SCHOLAR_CIRCLE,SECRET_SOCIETY,SPY_NETWORK};
	public static final FactionType[] ELEMENTAL = {DARK_CULT,HERETICAL_SECT,NATIONAL_CHURCH,RELIGIOUS_ORDER,RELIGIOUS_SECT,OUTLANDER_CLAN};
	public static final FactionType[] FEY = {DARK_CULT,RELIGIOUS_ORDER,
			ART_MOVEMENT,BEGGAR_GUILD,BLACK_MARKET,CONSPIRACY,CRIME_RING,GOURMAND_CLUB,HEIST_CREW,OUTLAW_GANG,RESISTANCE,SECRET_SOCIETY,SPY_NETWORK,STREET_ARTISTS,STREET_GANG,STREET_MUSICIANS,THEATER_TROUPE};
	public static final FactionType[] FIEND = {DARK_CULT,HERETICAL_SECT,NATIONAL_CHURCH,RELIGIOUS_ORDER,RELIGIOUS_SECT,
			BROTHERHOOD,CONSPIRACY,CRIME_FAMILY,CRIME_RING,HIRED_KILLERS,NOBLE_HOUSE,OUTLAW_GANG,POLITICAL_PARTY,RESISTANCE,ROYAL_HOUSE,SCHOLAR_CIRCLE,SECRET_SOCIETY,SPY_NETWORK,TRADE_COMPANY};
	public static final FactionType[] GIANT = {FREE_COMPANY,GOURMAND_CLUB,OUTLANDER_CLAN,OUTLANDER_CLAN,OUTLANDER_CLAN,OUTLANDER_CLAN,OUTLANDER_CLAN,OUTLAW_GANG,OUTLAW_GANG};
	public static final FactionType[] HUMANOID = FactionType.values();
	public static final FactionType[] MONSTROSITY = {DARK_CULT,OUTLANDER_CLAN,OUTLAW_GANG,EXPLORER_CLUB};
	public static final FactionType[] OOZE = {DARK_CULT,BEGGAR_GUILD,BLACK_MARKET,CRIME_RING,GOURMAND_CLUB,OUTLANDER_CLAN,OUTLAW_GANG,EXPLORER_CLUB,SPY_NETWORK,STREET_GANG};
	public static final FactionType[] PLANT = {DARK_CULT,OUTLANDER_CLAN,OUTLAW_GANG,EXPLORER_CLUB};
	public static final FactionType[] UNDEAD = FactionType.values();
	public static FactionType[] getFactionList(CreatureType type) {
		switch(type) {
		case ABERRATION: return ABERRATION;
		case BEAST: return BEAST;
		case CELESTIAL:return CELESTIAL;
		case CONSTRUCT:return CONSTRUCT;
		case DRAGON:return DRAGON;
		case ELEMENTAL:return ELEMENTAL;
		case FEY:return FEY;
		case FIEND:return FIEND;
		case GIANT:return GIANT;
		case HUMANOID:return HUMANOID;
		case MONSTROSITY:return MONSTROSITY;
		case OOZE:return OOZE;
		case PLANT:return PLANT;
		case UNDEAD:return UNDEAD;
		default: throw new UnsupportedOperationException("faction list not implemented for type: "+type.toString());
		}
	}

	String text;

	FactionType(String text) {
		this.text = text;
	}

	public String getText() {
		return text;
	}
	public String toString() {
		return text;
	}
	public boolean isFaith() {
		switch(this) {
		case DARK_CULT: case HERETICAL_SECT: case NATIONAL_CHURCH: case RELIGIOUS_ORDER: case RELIGIOUS_SECT:
			return true;
		default: return false;
		}
	}
}
