package names;

import data.Indexible;
import data.npc.NPCJobType;
import util.Util;

public enum FactionType {
	DARK_CULT,HERETICAL_SECT,NATIONAL_CHURCH,RELIGIOUS_ORDER,RELIGIOUS_SECT,DRUID_CIRCLE,MONASTIC_ORDER,

	ART_MOVEMENT,BARD_COLLEGE,BEGGAR_GUILD,BLACK_MARKET,BROTHERHOOD,CITY_GUARD,CONSPIRACY,CRAFT_GUILD,CRIME_FAMILY,CRIME_RING,EXPLORER_CLUB,FREE_COMPANY,GOURMAND_CLUB,HEIST_CREW,HIGH_COUNCIL,
	HIRED_KILLERS,LOCAL_MILITIA,NOBLE_HOUSE,OUTLANDER_CLAN,OUTLAW_GANG,POLITICAL_PARTY,KNIGHTLY_ORDER,RESISTANCE,ROYAL_ARMY,ROYAL_HOUSE,SCHOLAR_CIRCLE,SECRET_SOCIETY,SPY_NETWORK,STREET_ARTISTS,
	STREET_GANG,THEATER_TROUPE,TRADE_COMPANY,WIZARD_CIRCLE,
	
	AUTOCRACY,ELECTED_OFFICIAL,MONARCHY,PLUTOCRACY,ARISTOCRACY,THEOCRACY,CLANS,COMMUNE,ELECTED_COUNCIL;

	private static final FactionType[] FAITHS = {DARK_CULT,HERETICAL_SECT,NATIONAL_CHURCH,RELIGIOUS_ORDER,RELIGIOUS_SECT,DRUID_CIRCLE,MONASTIC_ORDER};
	private static final FactionType[] FACTIONS = {ART_MOVEMENT,BARD_COLLEGE,BEGGAR_GUILD,BLACK_MARKET,BROTHERHOOD,CITY_GUARD,CONSPIRACY,CRAFT_GUILD,CRIME_FAMILY,CRIME_RING,EXPLORER_CLUB,
			FREE_COMPANY,GOURMAND_CLUB,HEIST_CREW,HIGH_COUNCIL,HIRED_KILLERS,LOCAL_MILITIA,NOBLE_HOUSE,OUTLANDER_CLAN,OUTLAW_GANG,POLITICAL_PARTY,KNIGHTLY_ORDER,RESISTANCE,ROYAL_ARMY,
			ROYAL_HOUSE,SCHOLAR_CIRCLE,SECRET_SOCIETY,SPY_NETWORK,STREET_ARTISTS,STREET_GANG,THEATER_TROUPE,TRADE_COMPANY,WIZARD_CIRCLE};
	public static final FactionType[] ABERRATION = {DARK_CULT,DARK_CULT,DARK_CULT,DARK_CULT,DARK_CULT,HERETICAL_SECT,HERETICAL_SECT,HERETICAL_SECT,NATIONAL_CHURCH,RELIGIOUS_ORDER,RELIGIOUS_SECT,
			ART_MOVEMENT,BROTHERHOOD,CONSPIRACY,CRAFT_GUILD,EXPLORER_CLUB,NOBLE_HOUSE,SCHOLAR_CIRCLE,SECRET_SOCIETY,STREET_ARTISTS,BARD_COLLEGE,THEATER_TROUPE,WIZARD_CIRCLE};
	public static final FactionType[] BEAST = {DARK_CULT,DRUID_CIRCLE,OUTLANDER_CLAN,OUTLAW_GANG,EXPLORER_CLUB,WIZARD_CIRCLE};
	public static final FactionType[] CELESTIAL = {DARK_CULT,HERETICAL_SECT,NATIONAL_CHURCH,RELIGIOUS_ORDER,RELIGIOUS_SECT,MONASTIC_ORDER,
			BROTHERHOOD,CONSPIRACY,KNIGHTLY_ORDER,ROYAL_ARMY,ROYAL_HOUSE,NOBLE_HOUSE,SECRET_SOCIETY};
	public static final FactionType[] CONSTRUCT = {CONSPIRACY,CRAFT_GUILD,CRAFT_GUILD,CRAFT_GUILD,CRAFT_GUILD,CRIME_FAMILY,FREE_COMPANY,HIRED_KILLERS,OUTLAW_GANG,RESISTANCE,
			SCHOLAR_CIRCLE,SECRET_SOCIETY,SPY_NETWORK,WIZARD_CIRCLE};
	public static final FactionType[] DRAGON = {DARK_CULT,HERETICAL_SECT,NATIONAL_CHURCH,RELIGIOUS_ORDER,RELIGIOUS_SECT,MONASTIC_ORDER,
			CONSPIRACY,CRIME_FAMILY,CRIME_RING,GOURMAND_CLUB,HIGH_COUNCIL,KNIGHTLY_ORDER,NOBLE_HOUSE,OUTLANDER_CLAN,OUTLAW_GANG,POLITICAL_PARTY,ROYAL_HOUSE,SCHOLAR_CIRCLE,SECRET_SOCIETY,
			SPY_NETWORK,WIZARD_CIRCLE};
	public static final FactionType[] ELEMENTAL = {DARK_CULT,HERETICAL_SECT,NATIONAL_CHURCH,RELIGIOUS_ORDER,RELIGIOUS_SECT,DRUID_CIRCLE,MONASTIC_ORDER,OUTLANDER_CLAN};
	public static final FactionType[] FEY = {DARK_CULT,RELIGIOUS_ORDER,DRUID_CIRCLE,MONASTIC_ORDER,			
			ART_MOVEMENT,BEGGAR_GUILD,BLACK_MARKET,CONSPIRACY,CRIME_RING,GOURMAND_CLUB,HEIST_CREW,KNIGHTLY_ORDER,OUTLAW_GANG,RESISTANCE,SECRET_SOCIETY,SPY_NETWORK,STREET_ARTISTS,
			STREET_GANG,BARD_COLLEGE,THEATER_TROUPE};
	public static final FactionType[] FIEND = {DARK_CULT,HERETICAL_SECT,NATIONAL_CHURCH,RELIGIOUS_ORDER,RELIGIOUS_SECT,
			BROTHERHOOD,CONSPIRACY,CRIME_FAMILY,CRIME_RING,HIRED_KILLERS,KNIGHTLY_ORDER,NOBLE_HOUSE,OUTLAW_GANG,POLITICAL_PARTY,RESISTANCE,ROYAL_HOUSE,SCHOLAR_CIRCLE,SECRET_SOCIETY,
			SPY_NETWORK,TRADE_COMPANY,WIZARD_CIRCLE};
	public static final FactionType[] GIANT = {DRUID_CIRCLE,MONASTIC_ORDER,FREE_COMPANY,GOURMAND_CLUB,OUTLANDER_CLAN,OUTLANDER_CLAN,OUTLANDER_CLAN,OUTLANDER_CLAN,OUTLANDER_CLAN,OUTLAW_GANG,OUTLAW_GANG};
	public static final FactionType[] HUMANOID = FactionType.values();
	public static final FactionType[] MONSTROSITY = {DARK_CULT,DRUID_CIRCLE,OUTLANDER_CLAN,OUTLAW_GANG,EXPLORER_CLUB,WIZARD_CIRCLE};
	public static final FactionType[] OOZE = {DARK_CULT,DRUID_CIRCLE,BEGGAR_GUILD,BLACK_MARKET,CRIME_RING,GOURMAND_CLUB,OUTLANDER_CLAN,OUTLAW_GANG,EXPLORER_CLUB,SPY_NETWORK,STREET_GANG,WIZARD_CIRCLE};
	public static final FactionType[] PLANT = {DARK_CULT,DRUID_CIRCLE,OUTLANDER_CLAN,OUTLAW_GANG,EXPLORER_CLUB,WIZARD_CIRCLE};
	public static final FactionType[] UNDEAD = FactionType.values();
	
	public static final FactionType[] CITY_LEADERSHIP = {AUTOCRACY,ELECTED_OFFICIAL,MONARCHY,PLUTOCRACY,ARISTOCRACY,THEOCRACY,CLANS,COMMUNE,ELECTED_COUNCIL};

	public String toString() {
		return Util.toCamelCase(Util.replace(this.name(), "_", " "));
	}
	public boolean isFaith() {
		for(FactionType t:FAITHS) {
			if(this.equals(t)) return true;
		}
		return false;
	}
	

	public static FactionType getFaction(Indexible obj) {
		return (FactionType) Util.getElementFromArray(FACTIONS, obj);
	}
	public static FactionType getFaith(Indexible obj) {
		return (FactionType) Util.getElementFromArray(FAITHS, obj);
	}
	public NPCJobType[] getFactionJobs() {
		switch(this) {
		case DARK_CULT: return NPCJobType.DARK_CULT_JOBS;
		case HERETICAL_SECT: return NPCJobType.HERETICAL_SECT_JOBS;
		case NATIONAL_CHURCH: return NPCJobType.NATIONAL_CHURCH_JOBS;
		case RELIGIOUS_ORDER: return NPCJobType.RELIGIOUS_ORDER_JOBS;
		case RELIGIOUS_SECT: return NPCJobType.RELIGIOUS_SECT_JOBS;
		case DRUID_CIRCLE: return NPCJobType.DRUID_CIRCLE_JOBS;
		case MONASTIC_ORDER: return NPCJobType.MONASTIC_ORDER_JOBS;
		case ART_MOVEMENT: return NPCJobType.ART_MOVEMENT_JOBS;
		case BARD_COLLEGE: return NPCJobType.BARD_COLLEGE_JOBS;
		case BEGGAR_GUILD: return NPCJobType.BEGGAR_GUILD_JOBS;
		case BLACK_MARKET: return NPCJobType.BLACK_MARKET_JOBS;
		case BROTHERHOOD: return NPCJobType.BROTHERHOOD_JOBS;
		case CITY_GUARD: return NPCJobType.CITY_GUARD_JOBS;
		case CONSPIRACY: return NPCJobType.CONSPIRACY_JOBS;
		case CRAFT_GUILD: return NPCJobType.CRAFT_GUILD_JOBS;
		case CRIME_FAMILY: return NPCJobType.CRIME_FAMILY_JOBS;
		case CRIME_RING: return NPCJobType.CRIME_RING_JOBS;
		case EXPLORER_CLUB: return NPCJobType.EXPLORER_CLUB_JOBS;
		case FREE_COMPANY: return NPCJobType.FREE_COMPANY_JOBS;
		case GOURMAND_CLUB: return NPCJobType.GOURMAND_CLUB_JOBS;
		case HEIST_CREW: return NPCJobType.HEIST_CREW_JOBS;
		case HIGH_COUNCIL: return NPCJobType.HIGH_COUNCIL_JOBS;
		case HIRED_KILLERS: return NPCJobType.HIRED_KILLERS_JOBS;
		case LOCAL_MILITIA: return NPCJobType.LOCAL_MILITIA_JOBS;
		case NOBLE_HOUSE: return NPCJobType.NOBLE_HOUSE_JOBS;
		case OUTLANDER_CLAN: return NPCJobType.OUTLANDER_CLAN_JOBS;
		case OUTLAW_GANG: return NPCJobType.OUTLAW_GANG_JOBS;
		case POLITICAL_PARTY: return NPCJobType.POLITICAL_PARTY_JOBS;
		case KNIGHTLY_ORDER: return NPCJobType.KNIGHTLY_ORDER_JOBS;
		case RESISTANCE: return NPCJobType.RESISTANCE_JOBS;
		case ROYAL_ARMY: return NPCJobType.ROYAL_ARMY_JOBS;
		case ROYAL_HOUSE: return NPCJobType.ROYAL_HOUSE_JOBS;
		case SCHOLAR_CIRCLE: return NPCJobType.SCHOLAR_CIRCLE_JOBS;
		case SECRET_SOCIETY: return NPCJobType.SECRET_SOCIETY_JOBS;
		case SPY_NETWORK: return NPCJobType.SPY_NETWORK_JOBS;
		case STREET_ARTISTS: return NPCJobType.STREET_ARTISTS_JOBS;
		case STREET_GANG: return NPCJobType.STREET_GANG_JOBS;
		case THEATER_TROUPE: return NPCJobType.THEATER_TROUPE_JOBS;
		case TRADE_COMPANY: return NPCJobType.TRADE_COMPANY_JOBS;
		case WIZARD_CIRCLE: return NPCJobType.WIZARD_CIRCLE_JOBS;
		case AUTOCRACY: return NPCJobType.AUTOCRACY_JOBS;
		case ELECTED_OFFICIAL: return NPCJobType.ELECTED_OFFICIAL_JOBS;
		case MONARCHY: return NPCJobType.MONARCHY_JOBS;
		case PLUTOCRACY: return NPCJobType.PLUTOCRACY_JOBS;
		case ARISTOCRACY: return NPCJobType.ARISTOCRACY_JOBS;
		case THEOCRACY: return NPCJobType.THEOCRACY_JOBS;
		case CLANS: return NPCJobType.CLANS_JOBS;
		case COMMUNE: return NPCJobType.COMMUNE_JOBS;
		case ELECTED_COUNCIL: return NPCJobType.ELECTED_COUNCIL_JOBS;
		default:
			throw new IllegalArgumentException("Unrecognized factiontype: "+this);
		}
	}
}
